#!/bin/sh
#
# Name:        Program 1 - stats
# Author:      Scott Milton
# Date:        4/13/15
# Description: This shell script will... 
#
# general format for command is
# stats {-rows | cols} [input_file]

# temporary dummy variable to be replaced by command line option (rows or cols)
option='t'

# get process id for this program
TMP=ps$$
# set up trap to catch interrupt, hangup, and terminate signals and remove
# the temp file if program terminates unexpectedly (from intro to linux lecture)
trap "rm -f $TMP; exit 1" INT HUP TERM

# cat < file

# prompt user for input
echo 'Enter any number of integers separated by spaces.'
echo 'Push <ctrl> + d when finished.'

# get user input and store it in temp file
cat > TMP

# output contents of TMP file to stdout
cat TMP

if [ $option == 'r' ]
then
  echo 'Average Median'
elif [ $option == 'c' ]
then
  echo 'Averages:'
  echo 'Medians:'
else
  echo 'Usage: stats {-rows|-cols} [file]'
fi

# remove the temp file and exit normally
rm -f $TMP
exit 0
