#!/bin/sh
#
# Name:        Program 1 - stats
# Author:      Scott Milton
# Date:        4/13/15
# Description: This shell script will... 
#
# general format for command is
# stats {-rows | cols} [input_file]

option='c'

if [ $option == 'r' ]
then
  echo 'Average Median'
elif [ $option == 'c' ]
then
 echo 'Averages:'
 echo 'Medians:'
fi

