#!/bin/sh
#
# Name:        Program 1 - stats
# Author:      Scott Milton
# Date:        4/13/15
# Description: This shell script will... 
#
# general format for command is
# stats {-rows | cols} [input_file]

echo 'Hello world!'

